### ISSUE TITLE
Assert fail in unroll_tip_loops.py

### ISSUE THREAD

**Issue by snurk** [maickrau/verkko#11]
Unroll_tip_loops.py asserted on line 85.
```assert "<" + node in edges[revnode(edge)]```
Quickfix is in fea887280cf82f65ce5723646ac7f1edb8737a3e

Can be reproduced with intermediate outputs in /gpfs/gsfs7/users/nurks2/great_apes/bonobo/snakemake_mbg/test

**Comment by snurk** [comment]
@maickrau did you fix this one?

**Comment by maickrau** [comment]
fixed in 2a08912
