### ISSUE TITLE
HG002 ChrX split in par, missing last 1mb due to 2 gaps

### ISSUE THREAD

**Issue by skoren** [maickrau/verkko#4]
Latest version is still breaking. Both gaps <10kb and are scannable by ONT data. Red == maternal/blue == paternal.

<img width="567" alt="Screen Shot 2021-11-05 at 4 09 02 PM" src="https://user-images.githubusercontent.com/923478/140572349-268a84a3-9851-4864-89f8-86830446b3ba.png">

**Comment by snurk** [comment]
Fixed by correction, right

**Comment by skoren** [comment]
Latest graph on uncorrected data connects the par but only for the X, the Y PAR is only connected to the X component not the Y. The corrected graph connects X/Y par correctly but still one gap in the Y.
